server:
  port: 18086

spring:
  application:
    name: support-server
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/seckill?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

dubbo:
  application:
    name: support-server
    qos-enable: false
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
  protocol:
    name: dubbo
    port: 28080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
