server:
  port: 8085

spring:
  application:
    name: seckill-processor
  data:
    redis:
      host: localhost
      port: 6379

dubbo:
  application:
    name: seckill-processor
    qos-enable: false
  registry:
    address: nacos://127.0.0.1:8848
  consumer:
    check: false

rocketmq:
  name-server: 127.0.0.1:9876
  consumer:
    group: seckill-consumer-group
