server:
  port: 18084

spring:
  application:
    name: seckill-service
  config:
    import:
      - optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

dubbo:
  application:
    name: seckill-service
    qos-enable: false
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
  consumer:
    check: false

rocketmq:
  name-server: ${ROCKETMQ_ADDR}
  producer:
    group: seckill-producer-group
