server:
  port: 18082

spring:
  application:
    name: seckill-admin
  config:
    import:
      - optional:file:.env[.properties]

dubbo:
  application:
    name: seckill-admin
    qos-enable: false
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
  consumer:
    check: false

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
