server:
  port: 18083

spring:
  application:
    name: seckill-job
  config:
    import:
      - optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/xxl_job?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

dubbo:
  application:
    name: seckill-job
    qos-enable: false
  registry:
    address: nacos://${NACOS_ADDR}?username=${NACOS_USERNAME}&password=${NACOS_PASSWORD}
  consumer:
    check: false

xxl:
  job:
    admin:
      addresses: ${XXL_ADMIN_ADDR}
    executor:
      appname: seckill-job
      port: 19999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
